name: Jekyll site CI

sass:
    sass_dir: _sass

on:
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the site in the jekyll/builder container
      run: |
        !f() { git checkout master && git merge source && clear && echo '[BUILD]' && 
        jekyll && sass css/wouterj.scss css/wouterj.min.css --style compressed && 
        echo && echo '[COMMIT]' && git add -A && git add -f css/wouterj.min.css && 
        git commit -m 'Build website' && echo && echo '[PUSH]' && git push github master source && 
        git checkout --; }; f
